version: "3.7"

services:
  app:
    build: .
    ports:
      - "3021:3000"
    environment:
      - DATABASE_URL=postgres://user:password@host:port/database
      - PORT=3000
    volumes:
      - .env:/app/.env
