name: CI

on:
  push:
    branches: [main]

jobs:
  build_and_publish:
    name: ⚒️ Build and Publish Server Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: bitcoinnanolabs/faucet
